import { Component, OnInit } from '@angular/core';

function formatDateStr(date: string): string {
  // console.log(date);
  // date = date.replace(/\./g, '-');
  return date.replace(' ', 'T');
}

export type IDRecord = {
  gostNom: string,
  position: number|string,
  mainStr?: string,
  crossStr?: string,
  standardSize?: string,
  bracing?: string,
  skin?: string,
  performerID: number|string,
  qrCode: string,
  workType: number|string,
  date: string,
  firstRow: boolean,
};

@Component({
  selector: 'app-identifiers',
  templateUrl: './identifiers.component.html',
  styleUrls: ['./identifiers.component.sass']
})
export class IdentifiersComponent implements OnInit {
  public itemsPerPage = 15;
  public p = 0; // current page
  colNames: IDRecord = {
    gostNom: '№ Госта',
    position: 'Позиция',
    mainStr: 'Основная улица',
    crossStr: 'Пересек. улица',
    standardSize: 'Типоразмер',
    bracing: 'Тип крепления',
    skin: 'Тип пленки',
    performerID: 'Исполнитель',
    qrCode: 'QR код',
    workType: 'Вид работ',
    date: 'Дата',
    firstRow: true,
  };
  ids: IDRecord[];
  public drawbleIds: IDRecord[] = [];
  constructor() {
    this.ids = [
      {
        gostNom: '1.1',
        position: 1,
        mainStr: 'Ysyriska',
        crossStr: 'Ysyriyska',
        standardSize: 'Типоразмер ||',
        bracing: '',
        skin: '',
        performerID: 94,
        qrCode: 'QR SMEU14565411565',
        workType: 100,
        date: '2021-05-04 20:22:00',
        firstRow: false,
      },
      {
        gostNom: '2.1',
        position: 1,
        mainStr: 'frggrgr',
        crossStr: '4bdfbdr',
        standardSize: '3',
        bracing: '904',
        skin: '604',
        performerID: 19,
        qrCode: 'QR 2222222',
        workType: 60,
        date: '2021-05-01 20:22:00',
        firstRow: false,
      },
      {
        gostNom: '1.1',
        position: 1,
        mainStr: 'f',
        crossStr: '1',
        standardSize: '1',
        bracing: '1',
        skin: '0',
        performerID: 100,
        qrCode: 'QR 2222222',
        workType: 10,
        date: '2021-05-01 20:22:00',
        firstRow: false,
      },
      {
        gostNom: '2.1',
        position: 1,
        mainStr: 'frggrgr',
        crossStr: '4bdfbdr',
        standardSize: '3',
        bracing: '904',
        skin: '604',
        performerID: 19,
        qrCode: 'QR 2222222',
        workType: 60,
        date: '2021-05-03 20:22:00',
        firstRow: false,
      },
      {
        gostNom: '1.1',
        position: 1,
        mainStr: 'f',
        crossStr: '1',
        standardSize: '1',
        bracing: '1',
        skin: '0',
        performerID: 100,
        qrCode: 'QR 2222222',
        workType: 10,
        date: '2021-05-06 20:22:00',
        firstRow: false,
      },
      {
        gostNom: '2.1',
        position: 1,
        mainStr: 'frggrgr',
        crossStr: '4bdfbdr',
        standardSize: '3',
        bracing: '904',
        skin: '604',
        performerID: 19,
        qrCode: 'QR 2222222',
        workType: 60,
        date: '2021-04-01 20:22:00',
        firstRow: false,
      },
      {
        gostNom: '1.1',
        position: 1,
        mainStr: 'Ysyriska',
        crossStr: 'Ysyriyska',
        standardSize: 'Типоразмер ||',
        bracing: '',
        skin: '',
        performerID: 94,
        qrCode: 'QR SMEU14565411565',
        workType: 100,
        date: '2021-05-02 20:22:00',
        firstRow: false,
      },
      {
        gostNom: '2.1',
        position: 1,
        mainStr: 'frggrgr',
        crossStr: '4bdfbdr',
        standardSize: '3',
        bracing: '904',
        skin: '604',
        performerID: 19,
        qrCode: 'QR 2222222',
        workType: 60,
        date: '2021-05-01 20:22:00',
        firstRow: false,
      },
      {
        gostNom: '1.1',
        position: 1,
        mainStr: 'f',
        crossStr: '1',
        standardSize: '1',
        bracing: '1',
        skin: '0',
        performerID: 100,
        qrCode: 'QR 2222222',
        workType: 10,
        date: '2021-05-01 20:22:00',
        firstRow: false,
      },
      {
        gostNom: '2.1',
        position: 1,
        mainStr: 'frggrgr',
        crossStr: '4bdfbdr',
        standardSize: '3',
        bracing: '904',
        skin: '604',
        performerID: 19,
        qrCode: 'QR 2222222',
        workType: 60,
        date: '2021-05-01 20:22:00',
        firstRow: false,
      },
      {
        gostNom: '1.1',
        position: 1,
        mainStr: 'f',
        crossStr: '1',
        standardSize: '1',
        bracing: '1',
        skin: '0',
        performerID: 100,
        qrCode: 'QR 2222222',
        workType: 10,
        date: '2021-05-01 20:22:00',
        firstRow: false,
      },
      {
        gostNom: '2.1',
        position: 1,
        mainStr: 'frggrgr',
        crossStr: '4bdfbdr',
        standardSize: '3',
        bracing: '904',
        skin: '604',
        performerID: 19,
        qrCode: 'QR 2222222',
        workType: 60,
        date: '2021-05-01 20:22:00',
        firstRow: false,
      },
      {
        gostNom: '1.1',
        position: 1,
        mainStr: 'Ysyriska',
        crossStr: 'Ysyriyska',
        standardSize: 'Типоразмер ||',
        bracing: '',
        skin: '',
        performerID: 94,
        qrCode: 'QR SMEU14565411565',
        workType: 100,
        date: '2021-05-01 20:22:00',
        firstRow: false,
      },
      {
        gostNom: '2.1',
        position: 1,
        mainStr: 'frggrgr',
        crossStr: '4bdfbdr',
        standardSize: '3',
        bracing: '904',
        skin: '604',
        performerID: 19,
        qrCode: 'QR 2222222',
        workType: 60,
        date: '2021-05-01 20:22:00',
        firstRow: false,
      },
      {
        gostNom: '1.1',
        position: 1,
        mainStr: 'f',
        crossStr: '1',
        standardSize: '1',
        bracing: '1',
        skin: '0',
        performerID: 100,
        qrCode: 'QR 2222222',
        workType: 10,
        date: '2021-05-01 20:22:00',
        firstRow: false,
      },
      {
        gostNom: '2.1',
        position: 1,
        mainStr: 'frggrgr',
        crossStr: '4bdfbdr',
        standardSize: '3',
        bracing: '904',
        skin: '604',
        performerID: 19,
        qrCode: 'QR 2222222',
        workType: 60,
        date: '2021-05-01 20:22:00',
        firstRow: false,
      },
      {
        gostNom: '1.1',
        position: 1,
        mainStr: 'f',
        crossStr: '1',
        standardSize: '1',
        bracing: '1',
        skin: '0',
        performerID: 100,
        qrCode: 'QR 2222222',
        workType: 10,
        date: '2021-05-01 20:22:00',
        firstRow: false,
      },
      {
        gostNom: '2.1',
        position: 1,
        mainStr: 'frggrgr',
        crossStr: '4bdfbdr',
        standardSize: '3',
        bracing: '904',
        skin: '604',
        performerID: 19,
        qrCode: 'QR 2222222',
        workType: 60,
        date: '2021-05-01 20:22:00',
        firstRow: false,
      },
      {
        gostNom: '1.1',
        position: 1,
        mainStr: 'Ysyriska',
        crossStr: 'Ysyriyska',
        standardSize: 'Типоразмер ||',
        bracing: '',
        skin: '',
        performerID: 94,
        qrCode: 'QR SMEU14565411565',
        workType: 100,
        date: '2021-05-01 20:22:00',
        firstRow: false,
      },
      {
        gostNom: '2.1',
        position: 1,
        mainStr: 'frggrgr',
        crossStr: '4bdfbdr',
        standardSize: '3',
        bracing: '904',
        skin: '604',
        performerID: 19,
        qrCode: 'QR 2222222',
        workType: 60,
        date: '2021-05-01 20:22:00',
        firstRow: false,
      },
      {
        gostNom: '1.1',
        position: 1,
        mainStr: 'f',
        crossStr: '1',
        standardSize: '1',
        bracing: '1',
        skin: '0',
        performerID: 100,
        qrCode: 'QR 2222222',
        workType: 10,
        date: '2021-05-01 20:22:00',
        firstRow: false,
      },
      {
        gostNom: '2.1',
        position: 1,
        mainStr: 'frggrgr',
        crossStr: '4bdfbdr',
        standardSize: '3',
        bracing: '904',
        skin: '604',
        performerID: 19,
        qrCode: 'QR 2222222',
        workType: 60,
        date: '2021-05-01 20:22:00',
        firstRow: false,
      },
      {
        gostNom: '1.1',
        position: 1,
        mainStr: 'f',
        crossStr: '1',
        standardSize: '1',
        bracing: '1',
        skin: '0',
        performerID: 100,
        qrCode: 'QR 2222222',
        workType: 10,
        date: '2021-05-01 20:22:00',
        firstRow: false,
      },
      {
        gostNom: '2.1',
        position: 1,
        mainStr: 'frggrgr',
        crossStr: '4bdfbdr',
        standardSize: '3',
        bracing: '904',
        skin: '604',
        performerID: 19,
        qrCode: 'QR 2222222',
        workType: 60,
        date: '2021-05-01 20:22:00',
        firstRow: false,
      },
    ];
    this.drawbleIds = this.ids;
  }

  ngOnInit(): void {
  }

  filter(f: any): void {
    this.drawbleIds = this.ids.filter((id) => {
      console.log(Date.parse(formatDateStr(id.date)), Date.UTC(f.dateFrom.value.year, f.dateFrom.value.month, f.dateFrom.value.day),
        Date.parse(formatDateStr(id.date)), Date.UTC(f.dateTo.value.year, f.dateTo.value.month, f.dateTo.value.day),
        Date.parse(formatDateStr(id.date)) > Date.UTC(f.dateFrom.value.year, f.dateFrom.value.month, f.dateFrom.value.day) &&
        Date.parse(formatDateStr(id.date)) < Date.UTC(f.dateTo.value.year, f.dateTo.value.month, f.dateTo.value.day));
      return Date.parse(formatDateStr(id.date)) > Date.UTC(f.dateFrom.value.year, f.dateFrom.value.month, f.dateFrom.value.day) &&
        Date.parse(formatDateStr(id.date)) < Date.UTC(f.dateTo.value.year, f.dateTo.value.month, f.dateTo.value.day);
    });
  }

  get pageCount(): number {
    return Math.ceil(this.ids.length / this.itemsPerPage);
  }

  PaginationEvent(e: number): void {
    window.scroll(0, 0);
    this.p = e;
  }
}
